$env:MMS_INPUT_DIR = "C:/Users/walee/Documents/Thesis/MMS-Player/MMS-examples"
$env:AVASAG_CORPUS_DIR = "C:/Users/walee/Documents/Thesis/AVASAGcorpus-MLsubset91/AVASAGcorpus-MLsubset91"
$env:MMS_OUTPUT_DIR = "C:/Users/walee/Documents/Thesis/MMS-Player/inflected_mms"
$env:POINTING_DICT = "C:/Users/walee/Documents/Thesis/MMS-Player/pointing_dict.json"
$env:BLENDER_EXE="C:/Program Files/Blender Foundation/Blender 4.2/blender.exe"